<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "portfoliot_lafagnd"
 *
 * Auto generated by Extension Builder 2019-01-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Portfolio TL AF AG ND',
    'description' => 'portfolio_tlafagdn',
    'category' => 'plugin',
    'author' => 'Antoine Foré, Tanguy Laveau, Alexandre Gouguet, Nicolas Diot',
    'author_email' => 'fore.antoine@gmail.com, tang.laveau@hotmail.fr, alexandregouguet@gmail.com, nicolasdiot65@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
